name: 🚀 CI/CD - Hackathon Worker

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: hackathon-eks-cluster

jobs:
  test:
    name: 🧪 Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Checkout code
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install dependencies
        run: pip install -r requirements.txt

      - name: 🧪 Run tests
        run: python -m unittest discover tests

  deploy-worker:
    name: 🐳 Build & Deploy Worker
    runs-on: ubuntu-latest
    needs: test # Garante que este job só rode se o job 'test' passar
    steps:
      - uses: actions/checkout@v4

      - name: 🔐 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: 📦 Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO_WORKER }}

      - name: 🐳 Build and Push Docker Image
        run: |
          docker build -t hackathon-worker:latest .
          docker tag hackathon-worker:latest ${{ secrets.ECR_REPO_WORKER }}:latest
          docker push ${{ secrets.ECR_REPO_WORKER }}:latest

      - name: 🔌 Update Kubeconfig
        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.CLUSTER_NAME }}

      - name: 🤫 Create K8s Secrets dynamically
        run: |
          kubectl create secret generic hackathon-worker-secrets \
            --from-literal=DB_HOST="${{ secrets.DB_HOST }}" \
            --from-literal=DB_PORT="${{ secrets.DB_PORT }}" \
            --from-literal=DB_NAME="${{ secrets.DB_NAME }}" \
            --from-literal=DB_USER="${{ secrets.DB_USER }}" \
            --from-literal=DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            --from-literal=AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
            --from-literal=AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            --from-literal=AWS_SESSION_TOKEN="${{ secrets.AWS_SESSION_TOKEN }}" \
            --from-literal=AWS_DEFAULT_REGION="${{ env.AWS_REGION }}" \
            --from-literal=S3_BUCKET_NAME="${{ secrets.S3_BUCKET_NAME }}" \
            --from-literal=SQS_QUEUE_URL="${{ secrets.SQS_QUEUE_URL }}" \
            --from-literal=EMAIL_OFICINA="${{ secrets.EMAIL_OFICINA }}" \
            --from-literal=EMAIL_SENHA_APP="${{ secrets.EMAIL_SENHA_APP }}" \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: 🚀 Deploy App to K8s
        run: |
          sed -i "s|ECR_REPO_URL_PLACEHOLDER|${{ secrets.ECR_REPO_WORKER }}|g" k8s/deployment.yaml
          kubectl apply -f k8s/
          kubectl rollout restart deployment hackathon-worker-deployment